"use strict";

// console.log("gabi" + "salikhov")
// console.log("gabi" + "salikhov")

// incr , decr

// let incr = 12;
// let decr = 12;

// console.log(incr++)
// console.log(decr--)

// console.log(incr++)
// console.log(decr--)

// console.log(incr)
// console.log(decr)

// console.log(5 * 5 == 22)
// console.log(5 * 5 === "25")

// console.log(2 + 2 * 2 != 8)

// && = va || = yoki

// const yosh = true;
// const yopik = true;
// const joja = true;

// console.log(yosh && yopik && joja)

const namberOfSeries = +prompt("bugun siz nechta kino kordingiz?", "");

const SeriesDB = {
    count: namberOfSeries,
};

console.log(SeriesDB);